name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar ESLint
        run: npm run lint

      - name: Executar testes
        run: npm test

      - name: Executar build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Vincular projeto à Vercel
        run: vercel link --yes --project="$VERCEL_PROJECT_ID" --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Obter configurações da Vercel
        run: vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Gerar build da Vercel
        run: vercel build --prod --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Fazer o deploy na Vercel
        run: vercel deploy --prebuilt --prod --token="${{ secrets.VERCEL_TOKEN }}"
